// Generated by https://quicktype.io

export interface Media {
  media: MediaElement[];
}

export interface MediaElement {
  url:                 string;
  Country:             Country;
  Language:            Language;
  Topics:              string[];
  Contact_Email:       string;
  DF_Written_by_media: number;
  DF_written_by_us:    number;
  price_df_in_growwer: number | string;
  id:                  string;
}

export enum Country {
  Argentina = "Argentina",
  Chile = "Chile",
  Mexico = "Mexico",
  Spain = "Spain",
}

export enum Language {
  Spanish = "Spanish",
}
